### ISSUE TITLE
Error while running 'make setup'

### ISSUE THREAD

**Issue by JezWalmsley** [angelXwind/simject#55]
I keep on getting the error 'iPhone Developer: no identity found' and can't find how to bypass it. Any help?

**Comment by iAlex11** [comment]
Make sure you're not running the command as root (using `sudo` or `su`) since the keychain is different.

If you're not running the command as root, the problem is probably because the codesign flags are incorrect. 

Run `security find-identity -p codesigning` to get all the codesigning identities on your keychain and copy the code (which should be something like this `A1BB4274B6B119DD31EF2C51DIC7C0F0D99ES6P`), and then go to `/Users/alex/Documents/github/jailbreaking/theos/makefiles/targets/_common/darwin_head.mk`, and change 'TARGET_CODESIGN_FLAGS ?= --sign 'Apple Developer'` to `TARGET_CODESIGN_FLAGS ?= --sign 'CODE'` where CODE is the code you copied before.

Hope this helps you! It worked for me at least. :)

**Comment by kadirnanish** [comment]
ke sure you're not running the command as root (using sudo or su) since the keychain is different.

If you're not running the command as root, the problem is probably because the codesign flags are incorrect.

Run security find-identity -p codesigning to get all the codesigning identities on your keychain and copy the code (which should be something like this A2BB4274B6B119DD31EF2C51DIC7C0F0D99ES6P

**Comment by kadirnanish** [comment]
ke sure you're not running the command as root (using sudo or su) since the keychain is different.

If you're not running the command as root, the problem is probably because the codesign flags are incorrect.

Run security find-identity -p codesigning to get all the codesigning identities on your keychain and copy the code (which should be something like this A2BB4274B6B119DD31EF2C51DIC7C0F0D99ES6P
